##默认使用配置
spring:
  profiles:
    active: prod

##公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#mybatis:
#  typeAliasesPackage: com.nicho.bean
#  mapperLocations: classpath:mapper/*.xml


  redis:
    host: 192.168.137.3
    port: 6379
    poolMaxIdle: 500
    poolMaxTotal: 1000
    poolMaxWait: 500
    password: 123456
    timeout: 10


  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5

  rabbitmq:
    host: 192.168.137.3
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0

resources:
  add-mappings: true
  ache-period: 3600
  chain:
    cache: true
    enabled: true
    gzipped: true

    html-application-cache: true
  static-locations: calsspath:/static/



mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true


